### ISSUE TITLE
jitter and "MOS" calculation

### ISSUE THREAD

**Issue by ishmaelen** [sipcapture/statstrmr#2]
Hello,

This should probably have been reported to rtpsniff but I'm not confident rtpsniff is the best holder for this feature idea..

I see commented parts of rtpsniff code indicating some future jitter information. That is promising!

Would it be possible to even further enhance this to include "poor mans surface MoS" per e.g. PingPlotters implementation and it looks to be identical to Perl [Algorithm::MOS](http://cpansearch.perl.org/src/ADAMBA/Algorithm-MOS-0.001/lib/Algorithm/MOS.pm)

I know it's very far from optimal but it's advantage is that you do not need SIP SDP for codec or to analyze the actual stream (heavy). Also PingPlotter uses this method to indicate "MOS" for each hop in the route. mtr would be the linux equivalent except it doesn't have the MOS/Jitter.

Just dropping thoughts here but might be some idea to consider to test out and see what sort of results and how much discrepancy from "proper" MOS you'd get.

`EffectiveLatency = ( AverageLatency + Jitter * 2 + 10 )`
`if ER < 160 : R = 93.2 - (EffectiveLatency / 40)`
`if ER >= 160 : R = 93.2 - (EffectiveLatency - 120) / 10`
`R = R - (PacketLoss * 2.5)`
`MOS = 1 + (0.035) * R + (.000007) * R * (R-60) * (100-R)`

**Comment by lmangani** [comment]
Hi @ishmaelen indeed MOS is on the roadmap for both RTP and RTCP streams and we use a slight variant of the Perl MOS formula which works alright for estimations - just need to find time (or help) to complete the jitter calculation

**Comment by ishmaelen** [comment]
I think there exists some example in rtp_tap used in Wireshark found [here](https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob;f=ui/tap-rtp-common.c)

**Comment by lmangani** [comment]
the code is not the issue, time is ;)

**Comment by lmangani** [comment]
please open in rtpsnfff i'll push some test code to a branch if you want to test it
